spring.application.name=calculadora
server.port=8080

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# PostgreSQL (Máquina D)
spring.datasource.url=jdbc:postgresql://10.172.14.181:5432/personas_db
spring.datasource.username=personas_user
spring.datasource.password=personas123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.tomcat.relaxed-path-chars=_
server.tomcat.relaxed-query-chars=_
server.tomcat.max-http-header-size=32KB
